# Generated by Django 5.0.3 on 2024-03-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('taxId', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
    ]
