# Generated by Django 5.0.3 on 2024-03-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('created', 'CREATED'), ('sent', 'SENT'), ('error', 'ERROR'), ('paid', 'PAID')], default='created', max_length=7),
            preserve_default=False,
        ),
    ]
